# -*- coding: utf-8 -*-
"""lvadsusr136_aakashmurali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LARsT8rnf46SdIL7W0GSjPsScReNdCP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#1a loading the dataset

df=pd.read_csv('/content/Final Dataset - IPL.csv')
df

#1b understand the data

df.info() #structure of data
df.describe() #measures of data

#2a check and handle missing data

df.notnull().count() #as the count is 74(all data) therefore there are no missing , null values
#df.fillna(0).count() - if missing values existed... as there are no missing values , the na values no need to be handled

#2b resolve duplicates

df.duplicated()#as there are no duplicates present in this csv , it need not be handled
               #df.drop_duplicates() - if duplicates existed

#3 Analyse the measures like mean , median ...

numerical=df.select_dtypes(include=['int','float64']) # to find the numerical columns
print("Mean : ",numerical.mean(),"\n------------------\n")
print("Median : ",numerical.median(),"\n------------------\n")
print("Mode : ",numerical[['match_id','highscore']].mode(),"\n------------------\n")
print("Shape(range - r x c) : ",df.shape,"\n------------------\n")
print("std deviation : ",numerical.std() ,"\n------------------\n")

#or can also use describe() function to know these data:

print(df.describe())

#4 use charts and plots for visualization...

#we can use histogram to analyse the frequency of first innings wkts
plt.hist(df['first_ings_wkts'],bins=30)
plt.title("first innings wicket")
plt.show()

#we can use scatter plot to analyse the first and second ings scores
plt.scatter(numerical['first_ings_score'],numerical['second_ings_score'])
plt.title('first and second inning score')
plt.show()

#box plots are usually used in finding outliers etc , but not only for that
sns.boxplot(numerical['margin'])
plt.title("margin")
plt.show()
#bar charts are usually used for visualization of categories , here which team won how many matches
x=df.groupby('match_winner')['match_winner'].count()
plt.bar(x.index,x.values)
plt.xticks(rotation=90)
plt.grid()
plt.xlabel("wins")
plt.ylabel("teams")
plt.title("match winners teams")
plt.legend(x.index)
plt.show()

#pir charts are usually used to find the contribution of the same category
win=df.groupby('won_by')['match_winner'].count()
plt.pie(win,startangle=90,autopct='%1.1f%%')
plt.title("Winning teams reason")
plt.legend(win.index)
plt.show()

#4 cont...
#bar charts are usually used for visualization of categories , here which team won how many matches
x=df.groupby('match_winner')['match_winner'].count()
plt.bar(x.index,x.values)
plt.xticks(rotation=90)
plt.title("winners")
plt.show()

#pir charts are usually used to find the contribution of the same category
win=df.groupby('won_by')['match_winner'].count()
plt.pie(win,startangle=90,autopct='%1.1f%%')
plt.legend(win.index)
plt.title("winning reason")
plt.show()

#5 identifying relations between variables...
cor=numerical[['first_ings_score','first_ings_wkts']].corr()
sns.heatmap(cor, annot=True)
plt.title("relation btw 1st inn and wkts")
plt.show()

cor2=numerical[['second_ings_score','second_ings_wkts']].corr()
sns.heatmap(cor2, annot=True)
plt.title("relation btw 2nd inna dn wkts")
plt.show()

plt.scatter(numerical['first_ings_score'],numerical['second_ings_score'])
plt.show()

x2=df.groupby('toss_decision')['match_winner'].count()
plt.title("Toss desicion")
plt.pie(x2,autopct='%1.1f%%',startangle=90)
plt.legend(x2.index)
plt.show()

#6 identify the outliers ...

#as mentioned earlier , boxplots are commonly used to handle with the outliers
sns.boxplot(numerical) # our numerical dataframe
plt.title("outliers")
plt.xticks(rotation=90)

#7 compare team and individual performances across matches and venues..

venues=df.groupby('venue')['venue'].count()

print(team)#from here we can observe the performances of various teams over diff locations
#from the prev analysis , it is found that gujurat team has won most of matches and we are going to analyse that team to see the venues they won
x=df.groupby(['match_winner','venue'])['match_winner'].count()
print(x)

#8 key players performances

mof=df.groupby('player_of_the_match')['player_of_the_match'].count().nlargest(1)
topscorer=df.groupby('top_scorer')['top_scorer'].count().nlargest(1)
bestbowler=df.groupby('best_bowling')['best_bowling'].count().nlargest(1)

print(mof,bestbowler,topscorer)

"""#9

from all the above analysis it is found that team gujarat has won most of matches and also it is found that venue does playa a role in the winning chances.
About the key players , there are matches where those players are the main key reason for the victory of their teams. therefore i come to a conclusion that , not just the talent , but also the venue , key players , each and every ones contribution is important to the victory of a team
"""